django_project/django_project/urls.py
from django.conf.urls import include, url
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('users.urls', namespace="users")),
    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^$', views.index, name='index'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/product/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


from . import views
app_name = 'product'
urlpatterns = [
    url(r'^cadastrar/', views.cadastrar, name="cadastrarProduto"),
    url(r'^list_products/$', views.list_products, name="listproducts"),
    url(r'^create_category/', views.create_category, name="createcategory"),
    url(r'^edit_products/(?P<product_id>[0-9]+)/', views.edit_product, name="edit_product"),
    url(r'^delete_products/(?P<product_id>[0-9]+)/', views.delete_products, name="delete_products"),
    url(r'^delete_category/(?P<product_id>[0-9]+)/', views.delete_category, name="deletecategory"),
    url(r'^delete_sell/(?P<product_id>[0-9]+)/', views.delete_sell, name="deletesell"),
    url(r'^create_sell/', views.sell_product, name="sellproduct"),
]

static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/users/urls.py
from django.conf.urls import url

from . import views
app_name = 'users'
urlpatterns = [
    url(r'^dash/$', views.dashboard, name="dashboard"),
    url(r'^login/$', views.show_login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^self_edit/', views.self_edit_user, name="self_edit_user"),
    url(r'^register/', views.register, name="register"),
    url(r'^list_user_edit/', views.list_user_edit, name="listuseredit"),
    url(r'^list_user/', views.list_user, name="listuser"),
    url(r'^edit_user/(?P<user_id>[0-9]+)/', views.edit_user, name="edit_user"),
]

django_project/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Easy Service</title>


    <!-- Bootstrap Core CSS -->
    <link href="{% static 'users/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'users/css/landing-page.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'users/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="{% static 'text/css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="{% static 'users/text/css' %}">
    {% block head %}

    {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a style="padding-right:50px;" class="navbar-brand topnav" href="{% url "index"%}">Home</a>
                {% if user.is_authenticated %}
                <a href="{% url 'users:dashboard'%}">
                  <button type="button" class="btn btn-primary navbar-btn">
                  <span class="glyphicon glyphicon-scale"></span> {{ request.user.username }}
                </button>
              </a>
              {% endif %}
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#contact">Sobre</a>
                    </li>
                    {% if user.is_authenticated %}

                    <a href="{% url 'users:logout'%}?next=/">
                        <button type="button" class="btn btn-danger navbar-btn">
                        <span class= "glyphicon glyphicon-log-out" aria-hidden="true"> </span> Sair
                      </button>
                    </a>
                    {% else %}
                    <a href="{% url 'users:login'%}">
                        <button type="button" class="btn btn-default navbar-btn">
                        <span class= "glyphicon glyphicon-log-in" aria-hidden="true"> </span> Login
                      </button>
                    </a>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Header -->
    {% block body%}
    {% endblock%}

</body>

</html>

django_project/templates/index.html
{% extends "base.html"%}
{% load staticfiles %}

{% block head %}
{% endblock %}



{% block body%}

<a name="about"></a>
<div class="intro-header">
    <div class="container" style="padding-top:10px">

        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>EASY SERVICE</h1>
                    {% if user.is_authenticated %}
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a href="{% url "product:cadastrarProduto"%}" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="glyphicon glyphicon-folder-open"></span> Cadastrar Produto</span></a>
                        </li>
                        <li>
                            <a href="{% url "product:createcategory"%}" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="glyphicon glyphicon-flag"></span> Cadastrar Categoria</span></a>
                        </li>
                        <li>
                            <a href="{% url "product:sellproduct"%}" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="glyphicon glyphicon-shopping-cart"></span> Efetuar Venda</span></a>
                        </li>
                        <li>
                            <a href="{% url "product:listproducts"%}" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="glyphicon glyphicon-tasks"></span> Produtos</span></a>
                        </li>

                    </ul>
                    {% else %}
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.intro-header -->

<!-- Page Content -->

<a  name="services"></a>
<div class="content-section-a">

    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h4>O easy service é concentrado principalmente no controle de estoque automatizado,
              mas traz também vantagens no controle de Funcionários. Ao registrar a entrada de cada
              produto em estoque, é possível consultar todo o seu estoque, porém
              a baixa de estoque ainda é feita a partir de um produto por vez.
            </h4>

            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->


<!-- /.content-section-a -->

<a  name="contact"></a>
<div class="banner">

    <div class="container">

        <div class="row">
            <div class="col-lg-6">
            </div>
            <div class="col-lg-6">
                <ul class="list-inline banner-social-buttons">
                </ul>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.banner -->

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline">
                    <li>
                        <a href="#">Home</a>
                    </li>
                    <li class="footer-menu-divider">&sdot;</li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<!-- jQuery -->
<script src="{%static 'users/js/jquery.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{%static 'users/js/bootstrap.min.js' %}"></script>


{% endblock %}