django_project/django_project/urls.py
from django.conf.urls import include, url
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('users.urls', namespace="users")),
    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^$', views.index, name='index'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/product/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


from . import views
app_name = 'product'
urlpatterns = [
    url(r'^cadastrar/', views.cadastrar, name="cadastrarProduto"),
    url(r'^list_products/$', views.list_products, name="listproducts"),
    url(r'^create_category/', views.create_category, name="createcategory"),
    url(r'^edit_products/(?P<product_id>[0-9]+)/', views.edit_product, name="edit_product"),
    url(r'^delete_products/(?P<product_id>[0-9]+)/', views.delete_products, name="delete_products"),
    url(r'^delete_category/(?P<product_id>[0-9]+)/', views.delete_category, name="deletecategory"),
    url(r'^delete_sell/(?P<product_id>[0-9]+)/', views.delete_sell, name="deletesell"),
    url(r'^create_sell/', views.sell_product, name="sellproduct"),
]

static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/users/urls.py
from django.conf.urls import url

from . import views
app_name = 'users'
urlpatterns = [
    url(r'^dash/$', views.dashboard, name="dashboard"),
    url(r'^login/$', views.show_login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^self_edit/', views.self_edit_user, name="self_edit_user"),
    url(r'^register/', views.register, name="register"),
    url(r'^list_user_edit/', views.list_user_edit, name="listuseredit"),
    url(r'^list_user/', views.list_user, name="listuser"),
    url(r'^edit_user/(?P<user_id>[0-9]+)/', views.edit_user, name="edit_user"),
]

django_project/users/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

django_project/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Permission
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.admin.views.decorators import staff_member_required
from django.db import IntegrityError

@login_required
def dashboard(request):
    return render(request, 'users/dashboard.html')


def show_login(request):
    if request.method == "GET":
        return render(request, "users/login.html")
    else:
        context = make_login(request)

        if context.get('is_logged'):
            return HttpResponseRedirect(reverse("users:dashboard"))
        else:
            return render(request, "users/login.html", context)

@login_required
def logout_view(request, *args, **kwargs):

    return logout(request, *args, **kwargs)

def make_login(request):
    form = request.POST
    username = form.get('username')
    password = form.get('password')

    user = authenticate(username=username, password=password)
    is_logged = False

    if user is not None:
        login(request, user)
        message = "Logged"

        is_logged = True
    else:
        message = "Incorrect user"

    context = {
        "is_logged": is_logged,
        "message": message,
    }

    return context

def fullValidation(form):
    first_name = form.get('first_name')
    last_name = form.get('last_name')
    email = form.get('email')
    original_email = form.get('original_email')

    resultCheck = ''
    resultCheck += check_name(first_name, last_name)
    resultCheck += check_email(email)
    resultCheck += check_email_exist(email, original_email)

    return resultCheck


def fullValidationRegister(form, user=None):
    currentPassword = form.get('currentPassword')
    password = form.get('password')
    confirmPassword = form.get('confirmPassword')

    resultCheck = ''
    if user is not None:
        resultCheck += check_current_password(user, currentPassword)
        resultCheck += check_password_lenght(password, confirmPassword)
        resultCheck += check_password(password, confirmPassword)

    return resultCheck

def check_name(first_name, last_name):
    if not first_name.isalpha() or not last_name.isalpha():
        return 'Nome deve conter apenas letras'
    else:
        return ''


def check_email(email):
    if '@' not in email or '.' not in email or ' ' in email:
        return 'Email invalido'
    else:
        return ''


def check_email_exist(email, original_email):
    if User.objects.filter(email=email).exists() and email != original_email:
        return ' -- E-mail ja esta cadastrado no nosso banco de dados'
    else:
        return ''


def check_password_lenght(password, confirmPassword):
    if len(password) < 6 and password != confirmPassword:
        return ' -- Senha Invalida, digite uma senha com no minimo 6 letras'
    else:
        return ''


def check_password(password, confirmPassword):
    if password != confirmPassword:
        return ' -- Senha invalida! Senhas de cadastros diferentes'
    else:
        return ''


def check_current_password(user, currentPassword):

    if not user.check_password(currentPassword):
        return ' -- Campo de Senha atual diferente da Senha Atual!'
    else:
        return ''


@login_required
def self_edit_user(request):

    user = User.objects.get(pk=request.user.id)

    if request.method == "GET":
        return render(request, 'users/self_edit.html',)

    else:
        form = request.POST
        first_name = form.get('first_name')
        last_name = form.get('last_name')
        # email = form.get('email')
        email = request.user.username

        resultCheck = fullValidationRegister(form)
        resultCheck += fullValidation(form)

        user.first_name = first_name
        user.last_name = last_name
        user.username = email
        user.email = email
        user.save()

        # login(request,user)
        update_session_auth_hash(request, user)

        return render(request, 'users/dashboard.html')

@staff_member_required
def register(request):

    if request.method == "GET":
        return render(request, 'users/create_user.html')
    else:
        form = request.POST
        first_name = form.get('first_name')
        last_name = form.get('last_name')
        password = form.get('password')
        confirmPassword = form.get('confirmPassword')
        email = form.get('email')
        user_type = form.get('user_type')

        resultCheck = fullValidationRegister(form)
        resultCheck += fullValidation(form)

        if len(resultCheck) != 0:
            return render(
                request,
                'users/create_user.html',
                {'falha': resultCheck})

        try:
            if user_type == 'common':
                user = User.objects.create_user(first_name=first_name,
                                                last_name=last_name,
                                                password=password,
                                                username=email)
            else:
                user = User.objects.create_superuser(first_name=first_name,
                                                     last_name=last_name,
                                                     password=password,
                                                     username=email,
                                                     email=email)

        except IntegrityError as e:
            return render(request, 'users/create_user.html',
                          {'falha': 'Invalid email, email already exist'})
        except:
            return render(request, 'users/create_user.html',
                          {'falha': 'unexpected error'})

        user.save()
        messages.success(request, 'Usuario registrado com sucesso')


    return render(request, 'users/dashboard.html')


@staff_member_required
def list_user_edit(request):
    return __list__(request, 'users/list_user_edit.html')

@staff_member_required
def list_user(request):
    return __list__(request, 'users/list_user.html')

def __list__(request, template):

    users = User.objects.all()

    return render(request, template, {'users': users})

def __prepare_error_render__(request, fail_message, user):

    return render(request, 'userEdit/editUsers.html',
                  {'falha': fail_message, 'user': user})


def __prepare_error_render_self__(request, fail_message, user):

    return render(request, 'users/change_password.html',
                  {'falha': fail_message, 'user': user})



def check_permissions(user):
    context = {
        'user': user,
    }
    return context

@staff_member_required
def edit_user(request, user_id):

    user = User.objects.get(id=user_id)

    if request.method == "GET":
        context = check_permissions(user)
        return render(request, 'users/edit_user.html', context)

    else:
        form = request.POST
        first_name = form.get('first_name')
        last_name = form.get('last_name')
        email = form.get('email')
        user_type = form.get('user_type')
        resultCheck = fullValidation(form)

        if len(resultCheck) != 0:
            return __prepare_error_render__(request, resultCheck, user)

        user.first_name = first_name
        user.last_name = last_name
        user.username = email
        user.email = email

        if user_type == 'common':
            user.is_superuser = False
        else:
            user.is_staff = True


        context = check_permissions(user)
        user.save()
        context['info'] = 'usuario modificado com sucesso'

        return render(request, 'users/edit_user.html', context)


def __list__(request, template):

    users = User.objects.all()

    return render(request, template, {'users': users})

django_project/users/templates/users/create_user.html
{% extends 'base.html' %}

{% block title %}
<title>Novo Funcionário</title>
{% endblock %}

{% block  body %}

<div class="jumbotron">
  <div class="container">
    <div class="wrapper">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2>Registrar Novo Funcionário</h2>
          <form class="configdiv" action="register" method="post">
            <p2>{{falha}}</p2>
            {% csrf_token %}
            <div class="form-group">
              <input type="text" name= "first_name" placeholder="Nome" class="form-control">
            </div>
            <div class="form-group">
              <input type="text" name= "last_name" placeholder="Sobrenome" class="form-control">
            </div>
            <div class="form-group">
              <input type="text" name= "email" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" name ="password" placeholder="Senha" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" name ="confirmPassword" placeholder="Confirmar Senha" class="form-control">
            </div>


            <p1>Tipo de Usuário</p1>
            <div class="form-group" id="radios">
              <label class="radio-inline">
                <input type="radio" name="user_type" id="inlineRadio1" value="common"> Usuário Comum
              </label>
              <label class="radio-inline">
                <input type="radio" name="user_type" id="inlineRadio2" value="admin"> Adminsitrador
              </label>
            </div>
              <button type="submit" class="btn btn-success btn-lg btn-block" onclick="return confirm('Voce tem certeza ?')" > Registrar </button>

            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block login %}
<form class="navbar-form navbar-right" action="login" method="post">
  <p2 color="red" >{{falha}}</p2>
  {% csrf_token %}
  <div class="form-group">
    <input type="text" name= "Email" placeholder="Email" class="form-control">
  </div>
  <div class="form-group">
    <input type="password" name ="Password" placeholder="Password" class="form-control">
  </div>
  <button type="submit" class="btn btn-success">Sign in</button>
</form>
{% endblock %}

django_project/users/templates/users/dashboard.html
{% extends "base.html"%}

{% load staticfiles %}


{% block head %}
<title>Login/Sign-In</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
  <link href="{% static 'users/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'users/css/secondsidebarcss.css' %}" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}


{% block body %}
<nav class="navbar navbar-default sidebar" role="navigation" style="padding-top:50px">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Dashboard<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
        {% if user.is_staff %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuarios <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li><a href="{% url 'users:register' %}" class="glyphicons glyphicons-plus" >Adicionar Funcionário</a></li>
            <li><a href="{% url 'users:listuseredit' %}">Modificar Funcionário</a></li>
            <li><a href="{% url 'users:listuser' %}">Lista de Funcionários</a></li>

            <li><a href="#">Reportar</a></li>

          </ul>
        </li>
        {% endif %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Produtos <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li><a href="{% url 'product:cadastrarProduto' %}">Cadastrar Produto</a></li>
            <li><a href="{% url 'product:createcategory' %}">Cadastrar Categoria</a></li>
            <li><a href="{% url 'product:listproducts' %}">Lista de Protudos</a></li>
          </ul>
        </li>
        <li ><a href="{% url 'product:sellproduct' %}">Efetuar Venda<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-tags"></span></a></li>
      </ul>
    </div>
  </div>
</nav>

<header class="jumbotron hero-spacer" style="padding:180px;padding-left:250px;padding-top:180px">
    <h2>Bem Vindo {{ request.user.first_name }}<p></p></h2>
    <p>Fez alguma alteração em suas informações pessoais? Edite para manter o cadastro atualizado.</p>
      {% if user.is_authenticated %}
      <p><a href="{% url 'users:self_edit_user' %}" class="btn btn-primary btn-large">Editar Informações Pessoais</a>
      </p>
    {% endif%}
</header>

<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

  <script src="{%static 'users/js/index.js' %}"></script>
{% endblock %}

django_project/users/templates/users/edit_user.html
{% extends 'base.html' %}

{% block title %}
<title>Editar Funcionário</title>
{% endblock %}

{% block body %}
<div class="jumbotron">
  <div class="container">
    <div class="wrapper">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">

          <h1>Editar Funcionário</h1>

          <div class="confirmation">
            <p2>{{info}}</p2>
          </div>

          <h1> </h1>
          <form class="configdiv" action="register" method="post">
            <p2>{{falha}}</p2>
            {% csrf_token %}
            <div class="form-group">
              <input type="text" name= "first_name" value="{{user.first_name}}" class="form-control">
            </div>
            <div class="form-group">
              <input type="text" name= "last_name" value="{{user.last_name}}" class="form-control">
            </div>
            <div class="form-group">
              <input type="text" name= "email" value="{{user.email}}" class="form-control">
            </div>
            <p1>Tipo de Funcionário</p1>
            <div class="form-group">
              <label class="radio-inline">
                <input type="radio" name="user_type" id="inlineRadio1" value="common"> Funcionário Comum
              </label>
              <label class="radio-inline">
                <input type="radio" name="user_type" id="inlineRadio2" value="admin">Aministrador
              </label>

            <button type="submit" class="btn btn-success" onclick="return confirm('Voce tem certeza ?')" >Salvar</button>
            <input type="hidden" name="original_email" value="{{user.email}}">
            <a class="btn btn-primary" href="{% url 'users:listuseredit' %}" role="button">Cancelar</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block login %}
<form class="navbar-form navbar-right" action="login" method="post">
  <p2 color="red" >{{falha}}</p2>
  {% csrf_token %}
  <div class="form-group">
    <input type="text" name= "Email" placeholder="Email" class="form-control">
  </div>
  <div class="form-group">
    <input type="password" name ="Password" placeholder="Password" class="form-control">
  </div>
  <button type="submit" class="btn btn-success">Sign In</button>
</form>
{% endblock %}

django_project/users/templates/users/list_user.html
{% extends 'base.html' %}

{% block body %}


<div class="margin"style="padding-top:50px" >
  <h1 class="text-center">Lista de Funcionários Registrados</h>
  </div>

  <br />
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="margin">

        <table class ="table table-bordered">
          <tr>
              <th>Nome</th>
              <th>Sobrenome</th>
              <th>Email</th>
          </tr>
          {% for user in users %}
            {% if user.id != request.user.id %}
              <tr>
                <td>{{user.first_name}}</td>
                <td>{{user.last_name}}</td>
                <td>{{user.username}}</td>
              </tr>
            {% endif %}
          {% endfor %}
          </tab
        </div>
      </div>
    </div>


    {% endblock %}

django_project/users/templates/users/list_user_edit.html
{% extends 'base.html' %}

{% block body %}


<div class="margin"style="padding-top:50px" >
  <h1 class="text-center">Lista de Funcionários Registrados</h>
  </div>

  <br />
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="margin">

        <table class ="table table-bordered">
          <tr>
              <th>Nome</th>
              <th>Sobrenome</th>
              <th>Email</th>
              <th>Editar</th>
          </tr>
          {% for user in users %}
            {% if user.id != request.user.id %}
              <tr>
                <td>{{user.first_name}}</td>
                <td>{{user.last_name}}</td>
                <td>{{user.username}}</td>
                <td><a  class="glyphicon glyphicon-pencil" href="{% url 'users:edit_user' user.id %}"></a></td>
              </tr>
            {% endif %}
          {% endfor %}
          </tab
        </div>
      </div>
    </div>


    {% endblock %}

django_project/users/templates/users/login.html
{% extends "base.html"%}

{% load staticfiles %}


{% block head %}
<title>Login/Sign-In</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
  <link href="{% static 'users/css/style.css' %}" rel="stylesheet">
{% endblock %}




{% block body%}
  <div class="logmod">
  <div class="logmod__wrapper">

    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li style="padding-left:180px;"data-tabtar="lgm-2"><a href="#">Login</a></li
      </ul>
      <div class="logmod__tab lgm-2">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Insira o email e a senha <strong>para logar</strong></span>
        </div>
        <div class="logmod__form">
          <form class="form-signin" method="POST" action="{% url "users:login"%}">
            {% csrf_token %}
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">Email*</label>
                <input class="string optional" name="username" maxlength="255" id="user-email" placeholder="Email" type="email" size="50" />
              </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-pw">Password *</label>
                <input class="string optional" name="password" maxlength="255" id="user-pw" placeholder="Password" type="password" size="50" />
                						<span class="hide-password">Show</span>
              </div>
            </div>
            <div class="simform__actions">
              <button class="btn btn-info btn-primary btn-block" type="submit">Entrar</button>
              <span class="simform__actions-sidetext"><a class="special" role="link" href="#">Forgot your password?<br></a></span>
            </div>
          </form>
        </div>

          </div>
      </div>
    </div>
  </div>
</div>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src="{%static 'users/js/index.js' %}"></script>

{% endblock %}
</html>

django_project/users/templates/users/self_edit.html
{% extends "base.html"%}

{% block title %}
<title>Editar Conta</title>
{% endblock %}

{% block body %}
<div class="jumbotron">
  <div class="container">
    <div class="wrapper">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2>Editar Meus Dados</h2>
          <div class="confirmation">
            <p2>{{info}}</p2>
          </div>

          <h1> </h1>
          <form class="configdiv" action="register" method="post">
            <p2>{{falha}}</p2>
            {% csrf_token %}
            <div class="form-group">
              <p1>Nome</p1>
              <input type="text" name= "first_name" value="{{user.first_name}}" class="form-control">
            </div>
            <div class="form-group">
              <p1>Sobrenome</p1>
              <input type="text" name= "last_name" value="{{user.last_name}}" class="form-control">
            <div class="form-group">
              <p1>Email</p1>
              <input type="text" name= "email" value="{{user.email}}" class="form-control">
            </div>
            <input type="hidden" name="original_email" value="{{user.email}}">
                    <button type="submit" class="btn btn-success" onclick="return confirm('Voce tem certeza que deseja editar ?')" >Editar</button>
            <a class="btn btn-primary" href="{% url 'users:dashboard' %}" role="button">Cancelar</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block login %}
<form class="navbar-form navbar-right" action="login" method="post">
  <p2 color="red" >{{falha}}</p2>
  {% csrf_token %}
  <div class="form-group">
    <input type="text" name= "Email" placeholder="Email" class="form-control">
  </div>
  <div class="form-group">
    <input type="password" name ="Password" placeholder="Password" class="form-control">
  </div>
  <button type="submit" class="btn btn-success">Entrar</button>
</form>
{% endblock %}
Contact GitHub 