django_project/django_project/urls.py
from django.conf.urls import include, url
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('users.urls', namespace="users")),
    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^$', views.index, name='index'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/product/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


from . import views
app_name = 'product'
urlpatterns = [
    url(r'^cadastrar/', views.cadastrar, name="cadastrarProduto"),
    url(r'^list_products/$', views.list_products, name="listproducts"),
    url(r'^create_category/', views.create_category, name="createcategory"),
    url(r'^edit_products/(?P<product_id>[0-9]+)/', views.edit_product, name="edit_product"),
    url(r'^delete_products/(?P<product_id>[0-9]+)/', views.delete_products, name="delete_products"),
    url(r'^delete_category/(?P<product_id>[0-9]+)/', views.delete_category, name="deletecategory"),
    url(r'^delete_sell/(?P<product_id>[0-9]+)/', views.delete_sell, name="deletesell"),
    url(r'^create_sell/', views.sell_product, name="sellproduct"),
]

static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/users/urls.py
from django.conf.urls import url

from . import views
app_name = 'users'
urlpatterns = [
    url(r'^dash/$', views.dashboard, name="dashboard"),
    url(r'^login/$', views.show_login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^self_edit/', views.self_edit_user, name="self_edit_user"),
    url(r'^register/', views.register, name="register"),
    url(r'^list_user_edit/', views.list_user_edit, name="listuseredit"),
    url(r'^list_user/', views.list_user, name="listuser"),
    url(r'^edit_user/(?P<user_id>[0-9]+)/', views.edit_user, name="edit_user"),
]

django_project/product/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.category_name



class Product(models.Model):
    nome = models.CharField(max_length=30)
    quantidade = models.IntegerField()
    precoUnidade = models.DecimalField(max_digits=8, decimal_places=2)
    categories = models.ManyToManyField(Category, blank=True)
    picture = models.FileField(upload_to="product_", blank=True, null=True)

    def __str__(self):
        return self.nome


class Venda(models.Model):
    descricao = models.CharField(max_length=30, unique=True)
    quantidade = models.IntegerField(null=True)
    produtos = models.ManyToManyField(Product, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True)


    def __str__(self):
        return self.descricao

django_project/product/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product, Category, Venda



class Create_Product_Form(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        labels = {
            'nome': 'Nome do Produto',
            'precoUnidade': 'Preco',
            'quantidade': 'Quantidade',
            'categories': 'Categoria',
            'picture': 'Foto do Produto',

        }

        widgets = {
            'categories': forms.CheckboxSelectMultiple()
        }


class Create_Category_Form(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        labels = {
            'category_name': 'Nome da Categoria',
        }

class Create_Venda_Form(ModelForm):
    class Meta:
        model = Venda
        fields = '__all__'
        labels = {
            'descricao': 'Descricao',
            'quantidade': 'Quantidade',
            'produtos': 'Produtos',

        }
        widgets = {
            'produtos': forms.RadioSelect(),
            'quantidade': forms.NumberInput()
        }

django_project/product/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.admin.views.decorators import staff_member_required

from product.forms import Create_Category_Form, Create_Product_Form, Create_Venda_Form
from .models import Product, Category, Venda
from django.db import models
from django.contrib.auth.decorators import login_required

@login_required
def create_category(request):

    if request.method == "POST":
        form = Create_Category_Form(request.POST)
        if form.is_valid():
            form.save()
        return render(request, 'create_category.html', {'form': form, 'all_categories': Category.objects.all()})

    else:
        form = Create_Category_Form()
        return render(request, 'create_category.html', {'form': form, 'all_categories': Category.objects.all()})



@login_required
def cadastrar(request):
    if request.method == "POST":
        form = Create_Product_Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:listproducts'))
        return render(request, 'cadastrarProduto.html', {'form': form})

    else:
        form = Create_Product_Form()
        return render(request, 'cadastrarProduto.html', {'form': form})



@login_required
def edit_product(request,product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        form = Create_Product_Form(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:listproducts'))
        return render(request, 'edit_products.html', {'form': form})

    else:
        form = Create_Product_Form(instance=product)
        return render(request, 'edit_products.html', {'form': form})


@login_required
def sell_product(request):
    if request.method == "POST":
        form = Create_Venda_Form(request.POST, request.FILES)
        if form.is_valid():

            nomeProduto = form.cleaned_data.get('produtos')
            print nomeProduto[0]
            quantidade = form.cleaned_data.get('quantidade')

            try:
                allProducts = Product.objects.get(nome=nomeProduto[0])
                print allProducts
            except Product.DoesNotExist:
                allProducts = None
            if quantidade > allProducts.quantidade:
                return render(request, 'vendaproduto.html',
                             {'form': form, 'all_Venda': Venda.objects.all(), 'falha': 'Quantidade Insuficiente no estoque'})
            else:
                allProducts.quantidade -= quantidade
                allProducts.save()
                form.save()

            return HttpResponseRedirect(reverse('product:sellproduct'))
        return render(request, 'vendaproduto.html', {'form': form, 'all_Venda': Venda.objects.all()})

    else:
        form = Create_Venda_Form()
        return render(request, 'vendaproduto.html', {'form': form, 'all_Venda': Venda.objects.all()})


@login_required
def list_products(request):
    context = {
        'all_products': Product.objects.all(),
    }
    return render(request, 'list_products.html', context)

@login_required
def delete_products(request, product_id):
    Product.objects.get(id=product_id).delete()
    return HttpResponseRedirect(reverse('product:listproducts'))

@login_required
def delete_category(request, product_id):
    if request.method == "GET":
        Category.objects.get(id=product_id).delete()
        return HttpResponseRedirect(reverse('product:createcategory'))


@staff_member_required
def delete_sell(request, product_id):
    if request.method == "GET":
        Venda.objects.get(id=product_id).delete()
        return HttpResponseRedirect(reverse('product:sellproduct'))

django_project/product/templates/cadastrarProduto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}



<div class = "row">
  <div class="col-md-8 col-md-offset-1" style="padding-top:50px;">
    <div class="page-header">
    <h1>Cadastra Produto</h1>
    </div>


  <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    </br>
    <button type="submit" type="button" class="btn btn-success" onclick="return confirm('Voce tem certeza ?')">Cadastrar</button>
    <a class="btn btn-warning" href="{% url 'product:listproducts' %}">Cancelar</a>
  </form>
</div>
</div>

{% endblock %}

django_project/product/templates/create_category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}

 <div class="col-md-6 col-md-offset-3">
  <div class="col-md-8 col-md-offset-2" style="padding-top:50px;">
    <h1>Cadastra Categoria</h1>
    <br>
  </div>


  <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form|crispy}}

  </br>
    <button type="submit" type="button" class="btn btn-success" onclick="return confirm('Voce tem certeza ?')">Cadastrar</button>
    <a class="btn btn-warning" href="{% url 'product:listproducts' %}">Cancelar</a>
  </form>

  <table class="table table-hover" style="margin:5px;">
    <tr>
      <th>Nome</th>
      <th>Delete</th>
    </tr>
    {% for category in all_categories %}
    <tr>
      <td>{{category.category_name}}</td>
        <td><a class="glyphicon glyphicon-trash" onclick="return confirm('Voce tem certeza que deseja deletar ?   (Essa operação é irreversível)')" href="{% url 'product:deletecategory' category.id %}"></a></td>
      </tr>
    {% endfor %}
  </table>
</div>

{% endblock %}

django_project/product/templates/edit_products.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}

 <div class="col-md-6 col-md-offset-3">
  <div class="col-md-8 col-md-offset-2" style="padding-top:50px;">
    <h2>Editar Produto</h2>
    <br>
  </div>


  <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form|crispy}}


    <button type="submit" type="button" class="btn btn-success" onclick="return confirm('Voce tem certeza ?')">Salvar</button>
    <a class="btn btn-warning" href="{% url 'product:listproducts' %}">Cancelar</a>
  </form>

</div>

{% endblock %}

django_project/product/templates/list_products.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block head %}
{% endblock %}

{% block body %}
<div class = "container" style="padding:10px;display:table;">
<a class="btn btn-primary" href="{% url 'product:cadastrarProduto' %}">Adicionar Produto</a>
<table class="table table-hover" style="margin:5px;">

  <tr>

    <th>Foto</th>
    <th>Nome</th>
    <th>Quantidade</th>
    <th>Preço</th>
    <th>Categoria</th>

  </tr>
  {% for product in all_products %}
  <tr>

    <td> <img height="100" width="100" src= "{{ product.picture.url }}"></img> </td>
    <td>{{product.nome}}</td>
    <td>{{product.quantidade}}</td>
    <td>{{product.precoUnidade}}</td>

    {% for category in product.categories.all %}
      <td>{{category}}</td>
    {% endfor %}

    <td><a class="glyphicon glyphicon-trash" onclick="return confirm('Voce tem certeza que deseja deletar ?   (Essa operação é irreversível)')" href="{% url 'product:delete_products' product.id %}"></a></td>
    <td><a class="glyphicon glyphicon-pencil" href="{% url 'product:edit_product' product.id %}"></a></td>


  </tr>

  {% endfor %}
</table>

</div>
{% endblock %}

django_project/product/templates/vendaproduto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}


<div class = "row">
  <div class="col-md-8 col-md-offset-2" style="padding-top:50px;">
    <div class="page-header">
    <h1>Efetuar Venda</h1>
    </div>


  <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">

    {% csrf_token %}

    {{form|crispy}}



  </br
  ><button type="submit" type="button" class="btn btn-success" onclick="return confirm('Voce tem certeza ?')">Cadastrar</button>
    <a class="btn btn-warning" href="{% url 'product:listproducts' %}">Cancelar</a>
      <br><h3><a class="text-danger">{{falha}}</a><h3>
  </form>
  </div>
  </div>

  <div class = "row2">
    <div class="col-md-8 col-md-offset-2">
    </br>
  <table class="table table-hover">
    <tr>
      <th>Descricao</th>
      <th>Data de Venda</th>
      <th>Produto</th>
      <th>Quantidade<th>
      <th>Deletar</th>
    </tr>
    {% for venda in all_Venda %}
    <tr>
      <td>{{venda.descricao}}</td>
      <td>{{venda.date}}</td>
      {% for produtos in venda.produtos.all %}
      <td>{{produtos}}</td>
      {%endfor%}
      <td>{{venda.quantidade}}</td>
      <td><a class="glyphicon glyphicon-trash" onclick="return confirm('Voce tem certeza que deseja deletar ?   (Essa operação é irreversível)')" href="{% url 'product:deletesell' venda.id %}"></a></td>
      </tr>
    {% endfor %}
  </table>
  </div>
</div>

{% endblock %}